spring.application.name=aula2banco
spring.datasource.url=jdbc:postgresql://localhost:5432/api2026
spring.datasource.username=postgres
spring.datasource.password=2050
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true